#!/bin/bash

function usage (){
cat <<- :]
	Reset the given branch to match remote master.
	
	Usage:
	  `basename $0` [BRANCH]
	
	:]
}

BRANCH=${1-`git branch | sed -n 's/^* //p'`}
OUTBUF=brunch.$$
[ -f /dev/shm ] && export OUTBUF=/dev/shm/$OUTBUF || export OUTBUF=/tmp/$OUTBUF

echo Buffering to: $OUTBUF
exit 1

[ "$BRANCH" == "master" ] || [ "$BRANCH" == "" ] || [ "${BRANCH:0:1}" == '-' ] && {
  echo -e "WARN:  You'll need to break master personally nor will I do blanks.\n" >&2
  usage
  exit 1
}

git checkout master || exit 1
echo "[ENTER] to delete $BRANCH locally or [CTRL-C]"; read
git branch -D $BRANCH
echo "[ENTER] to delete $BRANCH remotely or [CTRL-C]"; read #Turn into an option
git push origin :$BRANCH
echo "[ENTER] to checkout $BRANCH and rebase or [CTRL-C]"; read #Turn into an option
git checkout -b $BRANCH && git rebase origin/master && git pull
